from decouple import config

DB_NAME = config("DB_NAME")
DB_USER = config("DB_USER")
DB_PASSWORD = config("DB_PASSWORD")
DB_HOST = "localhost"
DB_PORT = config("DB_PORT")

SECRET_KEY = config("SECRET_KEY")
FRONTEND_URL = config("FRONTEND_URL")

ACCESS_TOKEN_EXPIRE_MINUTES = int(config("ACCESS_TOKEN_EXPIRE_MINUTES"))
REFRESH_TOKEN_EXPIRE_MINUTES = int(config("REFRESH_TOKEN_EXPIRE_MINUTES"))

ALGORITHM = config("ALGORITHM")

# celery settings
CELERY_BROKER_URL = config("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = config("CELERY_RESULT_BACKEND")

EMAIL_USERNAME = config("EMAIL_USERNAME")
EMAIL_FROM = config("EMAIL_FROM")
EMAIL_PASSWORD = config("EMAIL_PASSWORD")

EMAIL_CONFIRM_EXPIRE_MINUTES = int(config("EMAIL_CONFIRM_EXPIRE_MINUTES"))

SMTP_PORT = config("SMTP_PORT")
SMTP_SERVER = config("SMTP_SERVER")